In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [6]:
df = pd.read_excel('sample_dataset.xlsx') # reading the dataset

In [7]:
print(df.head()) # printing the first 5 rows of the dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes


In [9]:
X = df.iloc[:, :-1].values #locating the features
y = df.iloc[:, -1].values #locating the target variable
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean') #creating the imputer
X[:, 1:3] = imputer.fit_transform(X[:, 1:3]) #imputing the missing values with the mean of the column
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [13]:
#encoding the categorical data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer( #creating the column transformer
    transformers=[('encoder', OneHotEncoder(), [0])], #encoding the first column
    remainder='passthrough' #passing through the rest of the columns
)
X = ct.fit_transform(X)
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [16]:
#label encoding the target variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() #creating the label encoder
y = le.fit_transform(y) #label encoding the target variable
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [17]:
#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42) #splitting the dataset into training and test sets, test size is 20% of the dataset, random state is 42 for reproducibility

In [20]:
#feature scaling
scaler = StandardScaler() #creating the scaler
X_train[:, 3:] = scaler.fit_transform(X_train[:, 3:]) #fitting and transforming the training set
X_test[:, 3:] = scaler.transform(X_test[:, 3:]) #transforming the test set


[[1.0 0.0 0.0 -0.7529426005471072 -0.6260377781240922]
 [1.0 0.0 0.0 1.0084538079529848 1.013042950055349]
 [1.0 0.0 0.0 1.791296656175248 1.8325833141450698]
 [0.0 1.0 0.0 -1.7314961608249362 -1.0943465576039326]
 [1.0 0.0 0.0 -0.36152117643597576 0.4276569757055486]
 [0.0 1.0 0.0 0.22561095973072165 0.05040823668012208]
 [0.0 0.0 1.0 -0.16581046438040992 -0.274806193514212]
 [0.0 0.0 1.0 -0.013591021670525259 -1.328500947343853]]
[[0.0 1.0 0.0 49.99999999999999 83000.0]
 [0.0 0.0 1.0 26.999999999999996 48000.0]]
